# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 441eb01db3f260b8c432750bef1465fdbeb2b8b3991a72c44fae17c082a899071496e8db433fff74ec294cc9356d61cf21311a36f6d118be3f5f4d91784c115d

test:
  secret_key_base: da886ccee79ff2fb14eed794c6b5bbed3ddb10751a72ce0345c9055aaf9229bd22c25c0a73ffc4e787728f7360e5f28b828e4ddf267a2638582252cfca4158ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
